name: CI/CD

on:
  push:
    branches: [ "main", "feature/*" ]

jobs:
  deploy-local:
    runs-on: self-hosted

    steps:
      - name: Descargar Código
        uses: actions/checkout@v4

      - name: Limpieza Extrema (Para no llenar los 8GB de AWS)
        run: |
          docker compose down -v --remove-orphans
          docker system prune -a -f
          docker builder prune -a -f
        continue-on-error: true

      - name: Configurar Secretos (Versión Linux para EC2)
        run: |
          mkdir -p secrets
          rm -rf secrets/*.txt

          printf "%s" "${{ secrets.DB_NAME }}" > secrets/db_name.txt
          printf "%s" "${{ secrets.DB_USER }}" > secrets/db_user.txt
          printf "%s" "${{ secrets.DB_PASSWORD }}" > secrets/db_password.txt
          printf "%s" "${{ secrets.MYSQL_ROOT_PASSWORD }}" > secrets/db_root_password.txt
          printf "%s" "${{ secrets.MYSQL_ROOT_PASSWORD }}" > secrets/mysql_root_password.txt
          
          chmod 600 secrets/*.txt
        shell: bash

      - name: Ejecutar Pruebas en Docker
        run: |
          docker compose build web
          docker compose run --rm --entrypoint "sh -c" web "pip install pytest httpx coverage && export PYTHONPATH=/app && pytest tests/ -v"

      - name: Despliegue Final
        if: success()
        run: |
          docker compose down --remove-orphans
          sleep 5
          docker compose up -d --build
          docker image prune -f

      - name: Limpieza en Fallo
        if: failure()
        run: |
          docker compose down -v